namespace:  
  name: staging


deployment:
  name: nginx-deployment
  namespace: staging
  replicas: 3
  image: nginx
  memory: 128Mi
  cpu: 50m
  imagepullpolicy: IfNotPresent
  imagetag: 1.18.0
  label:
    app: nginx

configmap:
  version: 1.18.0    

